export const mockedRepo: Repo = {
  id: 3222,
  name: 'media',
  owner: {
    login: 'github',
  },
  description: 'Media files for use in your GitHub integration projects',
  url: 'https://api.github.com/repos/github/media',
  pushed_at: '2015-02-27T17:31:20Z',
  size: 4484,
  language: null,
  forks: 62,
  open_issues: 0,
  watchers: 292,
}

export const mockedRepos: Repos = [
  {
    id: 3222,
    name: 'media',
    owner: {
      login: 'github',
    },
    description: 'Media files for use in your GitHub integration projects',
    url: 'https://api.github.com/repos/github/media',
    pushed_at: '2015-02-27T17:31:20Z',
    size: 4484,
    language: null,
    forks: 62,
    open_issues: 0,
    watchers: 292,
  },
  {
    id: 3222,
    name: 'media',
    owner: {
      login: 'github',
    },
    description: 'Media files for use in your GitHub integration projects',
    url: 'https://api.github.com/repos/github/media',
    pushed_at: '2015-02-27T17:31:20Z',
    size: 4484,
    language: null,
    forks: 62,
    open_issues: 0,
    watchers: 292,
  },
  {
    id: 3222,
    name: 'media',
    owner: {
      login: 'github',
    },
    description: 'Media files for use in your GitHub integration projects',
    url: 'https://api.github.com/repos/github/media',
    pushed_at: '2015-02-27T17:31:20Z',
    size: 4484,
    language: null,
    forks: 62,
    open_issues: 0,
    watchers: 292,
  },
  {
    id: 3222,
    name: 'media',
    owner: {
      login: 'github',
    },
    description: 'Media files for use in your GitHub integration projects',
    url: 'https://api.github.com/repos/github/media',
    pushed_at: '2015-02-27T17:31:20Z',
    size: 4484,
    language: null,
    forks: 62,
    open_issues: 0,
    watchers: 292,
  },
  {
    id: 3222,
    name: 'media',
    owner: {
      login: 'github',
    },
    description: 'Media files for use in your GitHub integration projects',
    url: 'https://api.github.com/repos/github/media',
    pushed_at: '2015-02-27T17:31:20Z',
    size: 4484,
    language: null,
    forks: 62,
    open_issues: 0,
    watchers: 292,
  },
]
